### ISSUE TITLE
Welcome email not sent

### ISSUE THREAD

**Issue by razbakov** [we-dance/platform#16]
Exception in Firebase:

```
Error: City Munich not found
    at exports.welcomeEmail.functions.firestore.document.onWrite (/workspace/lib/index.js:108:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by razbakov** [comment]
Welcome Email will be replaced with Hubspot.

**Comment by razbakov** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeDance-61e70d8b462b5400201aab2d/issues/we-dance/platform/16?planning-poker) with ZenHub @Stefanacef

**Comment by razbakov** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeDance-61e70d8b462b5400201aab2d/issues/we-dance/platform/16?planning-poker) with ZenHub @amanuela97 @nelson2411 @Stefanacef
